# Generated by Django 5.2.1 on 2025-05-28 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='job',
            field=models.ForeignKey(blank=True, db_column='job_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applicants', to='applications.job'),
        ),
    ]
