# Generated by Django 5.2.1 on 2025-05-28 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_applicants_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='applicant',
            field=models.ForeignKey(blank=True, db_column='applicant_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='skills', to='applications.applicants'),
        ),
    ]
